REM Cue file generated by Ardour
TITLE "Projekt"
FILE "Projekt.wav" WAVE
  TRACK 01 AUDIO
    FLAGS DCP 
    TITLE "mark1"
    INDEX 00 00:00:00
    INDEX 01 00:03:09
  TRACK 02 AUDIO
    FLAGS DCP 
    TITLE "mark2"
    INDEX 01 00:05:26
